### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by timito258** [timito258/protospace-37964#1]
https://protospace-37964.herokuapp.com/

**Comment by motomuun** [comment]
@timito258 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼した箇所はすべて修正出来ておりました！
前回確認出来なかった編集機能において、修正していただきたい箇所がございましたので、
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
投稿ができず、ページに留まった場合、入力済みの項目が消えてしまいます。消えないように修正をお願いします。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by timito258** [comment]
こちらでは正常に動作しておりますが、この場合はどのように対応すべきでしょうか。

**Comment by motomuun** [comment]
@timito258 さん、お問い合わせ頂きありがとうございます。
正常に動作出来ているとのことでしたので、詳細をお伺いできればと思います。

以下にお送り頂いたURLにて確認出来る現在の挙動と、正しい挙動、確認して頂きたい項目を記載させて頂きます。
お手数ですがご確認のほど、よろしくお願い致します。

[修正依頼箇所]
プロトタイプ編集機能

- [ ]  **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**

`現在の挙動`

https://user-images.githubusercontent.com/65059944/190548039-b7a2a326-914d-4dcc-89fa-119ae6a9ec82.mov

<img width="1440" alt="スクリーンショット 2022-09-16 12 02 48" src="https://user-images.githubusercontent.com/65059944/190548070-0d6c6dce-5b7f-4113-aaac-5e446d2e593c.png">

`正しい挙動`

https://user-images.githubusercontent.com/65059944/190548284-6d3c675f-5e62-4a07-981f-c1a2f634d5e3.mov

**確認頂きたいこと**

- [ ] 上記の正しい挙動の動画と同じ動作が出来ているか
- [ ] 本番環境で動作の確認ができるか
- [ ] マージやデプロイ忘れがないか


確認または修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by timito258** [comment]
修正箇所を勘違いしていました。
よろしくお願いします。
